theme: jekyll-theme-cayman
title: C칩mo representar a las Islas Malvinas en R y QGIS, usando Argenmap del Instituto Geogr치fico Nacional
description: Una discusi칩n sobre las Islas Malvinas en el mapa base de OpenStreetMap y los protocolos de visualizaci칩n con el mapa base de IGN.
